"use client";

import {
  MessageCircle,
  Video,
  Users,
  BookOpen,
  Target,
  Zap,
} from "lucide-react";

const features = [
  {
    icon: MessageCircle,
    title: "Structured Discussions",
    description:
      "Join topic-based discussions in scheduled meetings. No random chats — every session has a purpose.",
  },
  {
    icon: Video,
    title: "Google Meet-Style Calls",
    description:
      "Full video conferencing with screen sharing, chat, and participant management built right in.",
  },
  {
    icon: Users,
    title: "Community Driven",
    description:
      "Create or join communities of like-minded professionals. Build your network organically.",
  },
  {
    icon: BookOpen,
    title: "AI Topic Suggestions",
    description:
      "Get intelligent discussion topics generated by AI based on your community's interests and goals.",
  },
  {
    icon: Target,
    title: "Track Your Growth",
    description:
      "Earn points for participation, maintain streaks, and climb the leaderboard as you improve.",
  },
  {
    icon: Zap,
    title: "Meeting Summaries",
    description:
      "AI-powered summaries after each discussion capture key insights so nothing gets lost.",
  },
];

export default function Features() {
  return (
    <section
      id="features"
      style={{
        padding: "100px 24px",
        maxWidth: 1200,
        margin: "0 auto",
      }}
    >
      <div style={{ textAlign: "center", marginBottom: 64 }}>
        <h2 style={{ fontSize: "clamp(28px, 3.5vw, 40px)", marginBottom: 12 }}>
          Everything you need to grow
        </h2>
        <p
          style={{
            fontSize: 16,
            color: "var(--text-secondary)",
            maxWidth: 520,
            margin: "0 auto",
          }}
        >
          A complete platform for community-driven learning and professional
          development through real conversations.
        </p>
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
          gap: 16,
        }}
      >
        {features.map((feature) => {
          const Icon = feature.icon;
          return (
            <div key={feature.title} className="card" style={{ cursor: "default" }}>
              <div
                style={{
                  width: 40,
                  height: 40,
                  borderRadius: "var(--radius-md)",
                  background: "var(--accent-muted)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  marginBottom: 16,
                }}
              >
                <Icon size={20} color="var(--accent)" />
              </div>
              <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>
                {feature.title}
              </h3>
              <p
                style={{
                  fontSize: 14,
                  color: "var(--text-secondary)",
                  lineHeight: 1.6,
                }}
              >
                {feature.description}
              </p>
            </div>
          );
        })}
      </div>
    </section>
  );
}
