const fillerWords = ["um", "uh", "like", "actually", "basically", "you know"];

export function generateCoachReport(seedText: string) {
  const seed = Array.from(seedText).reduce((total, char) => total + char.charCodeAt(0), 0);
  const ratio = 35 + (seed % 31);
  const fillerWordCount = 3 + (seed % 14);
  const pacingWpm = 112 + (seed % 58);
  const clarityScore = Math.max(62, Math.min(98, 92 - Math.abs(142 - pacingWpm) / 2 - fillerWordCount));
  const confidenceScore = Math.max(58, Math.min(96, 70 + (seed % 23) - Math.max(0, fillerWordCount - 8)));
  const overallScore = Math.round((clarityScore + confidenceScore + (100 - Math.abs(50 - ratio))) / 3);
  const speakingTimeSeconds = 420 + (seed % 620);
  const listeningTimeSeconds = Math.round((speakingTimeSeconds * (100 - ratio)) / Math.max(ratio, 1));
  const trend = confidenceScore > 82 ? "rising" : confidenceScore < 68 ? "dipping" : "steady";
  const selectedFillers = fillerWords.slice(0, 4).map((word, index) => {
    const count = Math.max(0, Math.floor((fillerWordCount - index) / (index + 2)));
    return {
      word,
      count,
      severity: count > 5 ? "high" : count > 2 ? "medium" : "low",
    };
  });

  const actionItems = [
    ratio > 58 ? "Ask one open question before adding your next point." : "Volunteer an example earlier in the discussion.",
    pacingWpm > 155 ? "Pause for one beat after important sentences." : "Keep your current pace, then add stronger emphasis on conclusions.",
    fillerWordCount > 9 ? "Replace filler words with a short breath or silent pause." : "Maintain your low-filler delivery in the next room.",
  ];

  const badgesEarned = [
    overallScore >= 85 ? "Clear Communicator" : "Growth Sprint",
    ratio >= 43 && ratio <= 57 ? "Balanced Contributor" : "Active Participant",
    fillerWordCount <= 7 ? "Low Filler Focus" : "Practice Builder",
  ];

  return {
    talkToListenRatio: ratio,
    speakingTimeSeconds,
    listeningTimeSeconds,
    clarityScore: Math.round(clarityScore),
    confidenceScore: Math.round(confidenceScore),
    confidenceTrend: trend,
    fillerWordCount,
    fillerHeatmap: selectedFillers,
    pacingWpm,
    overallScore,
    summary:
      "Your session showed a useful mix of participation, listening, and reflection. The strongest improvement opportunity is turning pauses into intentional structure.",
    transcript:
      "Transcript capture is ready for a LiveKit Agent or speech-to-text provider. Once connected, this field stores the session transcript for review.",
    feedback: [
      "### AI Meeting Coach",
      "",
      `**Speaking time**: You spoke for about ${Math.round(speakingTimeSeconds / 60)} minutes and kept a ${ratio}/${100 - ratio} talk-to-listen balance.`,
      "",
      `**Clarity**: Your clarity score is ${Math.round(clarityScore)}. Shorter sentences and stronger signposting will make your best points land faster.`,
      "",
      `**Confidence**: Your confidence trend is ${trend}. Keep using concrete examples; they make your delivery feel more grounded.`,
      "",
      `**Fillers**: ${fillerWordCount} filler words were detected in the simulated coach pass. Use a quiet pause when you feel the next thought forming.`,
      "",
      "---",
      "",
      "*This report is generated by OpenGrow's coach engine. Connect a LiveKit Agent/STT provider to replace simulated metrics with realtime media analysis.*",
    ].join("\n"),
    actionItems,
    tryNextTime:
      "Open with one concise point, ask a follow-up question, then close with a 15-second summary of what you learned.",
    badgesEarned,
    nextGoals: [
      "Keep filler words below 8",
      "Stay between 130 and 150 words per minute",
      "Ask at least two follow-up questions",
    ],
  };
}
